### ISSUE TITLE
Hi, quick question.

### ISSUE THREAD

**Issue by JackDinn** [equalsgibson/golibre#1]
I see that you have updated your API access to LibreLinkUp/LibreView a couple of days ago.
I just wondered if you know if the Libre developers have changed the API access to `https://api-eu2.libreview.io` a few hours ago?

I have written an application that access the API, but tonight their servers went off-line and when they came back on my applications API access had stopped working.

Im sorry to ask you here but i dont know how to do a direct message in github.

 it's possible that the API endpoint or required headers have changed. The API might now expect different headers, a different version number, or even a different authentication method. Are you aware of any changes or where i can find the up to date documentation for accessing the API.

Best Regards,
Jack.

**Comment by equalsgibson** [comment]
Hey Jack, 

I had some issues connecting earlier this morning using the baseURL of "api.libreview.io", but I have tried again just now and I can access the data as normal. 

It could be that the Libre team were updating their app and it was temporarily unavailable on that host 

I don't have any access to the documentation unfortunately. I have pieced together what I can from sources online, but there is nothing official from Abbott / Libre that I can find.

**Comment by JackDinn** [comment]
Hi, thx for the response,

I just don't know, i have no clue who to contact. :cry:  All i can do it troll anywhere that is even slightly involved.

I installed this chaps script and it also gives the same error. I also posted to him as well.

https://github.com/DiaKEM/libre-link-up-api-client/issues/24

**Comment by JackDinn** [comment]
Im trying to get your code to do something but i have no idea about go. 

I have installed go, all looks ok.

I cloned your package 

```
⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼ /home/greg/git/golibre ⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼
❱lll
Permissions Size User Group Date Modified Date Created Name
drwxr-xr-x     - greg greg  25 Sep 13:21  25 Sep 13:21  .
drwxr-xr-x     - greg greg  25 Sep 13:21  13 Jul 07:31  ..
drwxr-xr-x     - greg greg  25 Sep 13:21  25 Sep 13:21  .git
drwxr-xr-x     - greg greg  25 Sep 13:21  25 Sep 13:21  docs
drwxr-xr-x     - greg greg  25 Sep 13:21  25 Sep 13:21  golibre
.rw-r--r--   507 greg greg  25 Sep 13:21  25 Sep 13:21  .gitignore
.rw-r--r--   246 greg greg  25 Sep 13:21  25 Sep 13:21  .golangci.yml
.rw-r--r--    50 greg greg  25 Sep 13:21  25 Sep 13:21  go.mod
.rw-r--r--     0 greg greg  25 Sep 13:21  25 Sep 13:21  go.sum
.rw-r--r--   35k greg greg  25 Sep 13:21  25 Sep 13:21  LICENSE
.rw-r--r--    45 greg greg  25 Sep 13:21  25 Sep 13:21  README.md

```

But i dont know how to test a connection from here, please advise. 

Thank you.

**Comment by equalsgibson** [comment]
Hey Jack!

I should have an example created and an updated readme shortly. This should give step by step instructions on how to get data for a single "connection"

Do you have valid LibreLinkUp credentials and has someone invited you to share their CGM data? Best way to test that is to download the LibreLinkUp app from either the iOS store or the Google play store.

I'll ping you when the readme is updated :)

**Comment by JackDinn** [comment]
Hi Rob, 
I have had feedback from the scatter gun of messages i sent out to anyone that might even have the closest of contact with the Libra API. I have found that even me logging out and back in was not quite enough for me, i had to log out of all of my devices (and i had a couple like a SugarPixel device). Once i had figured out that i needed to log out of all of them and then log back in on one of my androids it then did present the EULA.

Im happy again now.

Thank you very much for the response :)

https://github.com/robberwick/pylibrelinkup/issues/11#issuecomment-2374546476
